### ISSUE TITLE
[FI] Need help fixing Finnish numbering

### ISSUE THREAD

**Issue by salleq** [rhasspy/unicode-rbnf#2]
I don't know if this is the correct place to open this issue, but here goes:

In Finnish language the numbers as written text are not correctly translated to actual numbers in the following cases:

21-29 (kaksikymmentäXX  or in English "twentyXX")
31-39 (kolmekymmentäXX "thirtyXX")
41-49 (neljäkymmentäXX "fortyXX")

...and so on. From 1-19 it works correctly, and all full tens (20 "kaksikymmentä", 30 "kolmekymmentä", 40 "neljäkymmentä" etc.) work correctly as well.

Tested also that 100 ("sata") works correctly but 101 ("satayksi") does not, and after 100 even the full tens do not work (110).

I could test out/try to fix this myself as well but I couldn't figure out how to set up the environment to do this. Obviously I could just type the literal "kaksikymmentäviisi" (25) for each number but I guess that's not optimal way to do this.

**Comment by synesthesiam** [comment]
Thanks! Fixed in 1.3.0 :slightly_smiling_face:
